### ISSUE TITLE
Less-than sign must be encoded for XML output

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#103]
To avoid invalid documents, Less-than '<' in data to be output via XML must be encoded as `&#60;`

printController::generate_xml

**Comment by steveblamey** [comment]
First commit was incorrect. That's what you get for coding on a Saturday :)

**Comment by mshiner** [comment]
FYI This applies to all documents output by FOP - I tripped over this last year on an invoice.
