### ISSUE TITLE
Deleting an account or person contact fails

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#116]
Deleting an account contact fails and displays an empty page in the browser

**Comment by mshiner** [comment]
Have seen this before I think.... thought it was fixed ages ago. 

Just tried myself and it is also impossible to delete a person record.

**Comment by steveblamey** [comment]
If you look at the code for the delete action on the companys(sic) controller, you will see a couple of exit statements. I think somebody started looking at it in the past and never finished.

If you remove the exists, it then fails with a message: Cannot find Address record. It gets the wrong address id somehow. If you delete that address first, it works.

**Comment by mshiner** [comment]
@steveblamey 

I'd like to bump this up the priority hierarchy if possible.

**Comment by steveblamey** [comment]
Review this in conjunction with #8
