### ISSUE TITLE
Allow owner of purchase order to be changed

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#126]
Once a purchase order is part received the owner cannot be changed. This prevents other users from editing the lines to indicate where they should be marked complete on short deliveries.

There should be a controller action that allows the owner to be changed by any user that has permission to do so. It may also be useful to have a module setting that disables 'can_edit' checking for all users so that any user that has permission to edit purchase orders can edit lines on any PO.

**Comment by mshiner** [comment]
Is this a duplicate of #18 ?

**Comment by steveblamey** [comment]
Closed as duplcate, see #18
