### ISSUE TITLE
Link between Component Class and Type code needs to be enforced (2-1102)

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#13]
There is link between Comp Class and Type Code on Stock Items. However, this link is not currently enforced. One option would be to remove the Comp Class from Stock Item and add it to Type Code. This would then enable the Type Code list on the Work Orders search screen to be restricted to codes within comp class for which works orders can be raised.

**Comment by steveblamey** [comment]
At present the link is implied and there is an issue if you don't keep them in synch then the route (defined by type code) will not match the context for the item (defined by comp class). Effectively the type codes should be holding the component class.

**Comment by mshiner** [comment]
Step1
Add to the type code model the component class which is one of Bought In, Manufactured or Sub contract (hard coded). Within the type code UI when adding ajax the ability to add actions such that Bought in doesn't allow actions to be added. Do not allow the comp class to be edited for a type code.

Step 2
Within the adding of a stock item reverse the type code and comp class drop-downs and ajax the type code to restrict the list based on the comp class selection.
