### ISSUE TITLE
Authorising and Posting expenses

### ISSUE THREAD

**Issue by mshiner** [uzerpllp/uzerp#130]
When authorising and posting expenses the change of status should just 'happen'
Here is the expense action
pid=953&module=hr&controller=expenses&action=view&id=264

pid=627&module=hr&controller=expenses&action=confirmRequest&id=265

Note Post to Ledger sets status to be Awaiting Payment

**Comment by steveblamey** [comment]
The drop-down that allows a new status to be selected must be removed.
