### ISSUE TITLE
Pay or receive VAT in cashbook

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#136]
## Issue
When you have to pay or receive VAT from HMRC you can't through the cashbook as VAT is a control account.

## Workaround
The workaround is to change the VAT control to non-control and do the payment then change it back OR set up a recurring payment/receipt while the control is of.

## Suggested Fix
I think we should have a sidebar link that says "Pay or receive VAT from HMRC" that creates a CB transaction for you without having to change the VAT account control status.

**Comment by mshiner** [comment]
More detail in the file attached
[Pay or receive VAT.pdf](https://github.com/uzerpllp/uzerp/files/2124512/Pay.or.receive.VAT.pdf)

**Comment by steveblamey** [comment]
https://github.com/uzerpllp/uzerp/commit/565c2154b09787193d3c61769844ca7405a4edd5
