### ISSUE TITLE
GL opening balance journal

### ISSUE THREAD

**Issue by mshiner** [uzerpllp/uzerp#147]
Opening balance required - this is a new journal type in GL headers 

lines restricted as follows

1. balance sheet accounts only
2. non-control accounts
3. default period 0 for current year
4. no accruals

**Comment by mshiner** [comment]
Also

Set transaction date as end date of period 0

**Comment by mshiner** [comment]
[GL opening balance journal.pdf](https://github.com/uzerpllp/uzerp/files/2124634/GL.opening.balance.journal.pdf)

**Comment by mshiner** [comment]
I have fleshed out the requirement. Tack changed as I think we should actually post the journal into period 12 of the closed year (or whatever period number is the last period) and adjust the balances on glbalances both for that period AND period ZERO of the new year.

There is a wrinkle in that there is a  gl_period_end_balances table that is created by the closing routine, although I am unsure what it contains and where it is used. We need to update this table also I think but if it is cumulative there may be a lot of overhead in doing this. Can you ascertain where it is used and I will take a look at what it does.

**Comment by steveblamey** [comment]
@mshiner See modules/public_pages/erp/ledger/models/periodHandling.php. That is the only reference I can find and the data doesn't appear to be used anywhere, but there may be reports based on it.

**Comment by mshiner** [comment]
Changed the priority on this as it is an overdue fix which will increasingly come into focus... potentially as a showstopper.

**Comment by mshiner** [comment]
[GL opening balance journal.pdf](https://github.com/uzerpllp/uzerp/files/3710840/GL.opening.balance.journal.pdf)
Updated the spec with additional notes

**Comment by steveblamey** [comment]
@mshiner this has been merged, ready for you to test.

**Comment by mshiner** [comment]
@steveblamey I'll take a look and let you know

**Comment by mshiner** [comment]
Posted 4 journals into a copy DB and checked each one individually - they all work exactly as expected. Good Job!
