### ISSUE TITLE
Reprint Work Order Documents

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#148]
Add the ability to 'reprint' the document set, or individual documents, from within a works order. The set could be via a sidebar link whereas the individual documents could be printed from the links (which don't work at the moment)

Moved from https://github.com/uzerpllp/uzerp/issues/98

**Comment by steveblamey** [comment]
@mshiner can you explain what doesn't work when reprinting from within the Work Order? Are particular documents affected? My testing shows that is does work.

**Comment by mshiner** [comment]
Steve

The issue is that there is no option to print in the sidebar of a works order plus you have to print the whole set from the uzlet, so you cannot reprint an individual document.

**Comment by steveblamey** [comment]
@mshiner I understand the lack of print all, but when testing I can click the links and get output of individual documents. You seemed to be saying that those links are not working.

**Comment by steveblamey** [comment]
Injector classes need updating so the correct report definition is selected. Works Order document printing will be refactored to use checkbox selection of documents and those classes will be fixed at the same time.

**Comment by steveblamey** [comment]
Closed with commit: 97b91c875adbd689a929d0eb12923696da564305
