### ISSUE TITLE
Return goods from works order (4-1699)

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#16]
Goods are issued to a works order using the Issue action. Each issue action has a transfer rule (only 1) which defines the movement. The issue action to be used is defined by product type so when an issue takes place the code checks which action/rule to use.

This allows different product types to have defined material 'routes' through the plant. However the new manufacturing functionality means a return from a works order is defined by a Return action rather than just reversing the Issue action as previously - this means that the Return action must be defined by product type and the code needs to check which action (and hence which transfer rule) to use when returning stock from a works order.

On the screen to issue or return to a WO the action needs to be constrained based on the entries in the type code. If issue/return is Null allow all issue or return actions in drop down.

**Comment by mshiner** [comment]
Link this work with item #13 as its is in the same area. We need to add the ability to add a return action to a type code.

**Comment by steveblamey** [comment]
The merge above adds a return action selection into the type code UI, enabling returns to work from Work Orders.
