### ISSUE TITLE
Select supplier currency in Purchase Product Lines

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#162]
When entering a new Purchased Product Line for a specific supplier, the currency must be automatically selected to match the currency on the suppliers ledger account.

**Comment by mshiner** [comment]
Does this issue apply to SO product lines as well?

**Comment by steveblamey** [comment]
Not sure why this was added, the supplier currency is already defaulted form the supplier for both SO and PO productlines when the customer/supplier is selected.
