### ISSUE TITLE
Cash book, move money UI

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#165]
When a transfer is made between bank accounts the currency rate defaults to the rate required to do the transfer correctly based on the default rate in the currency table. In addition the form sets the currency to be transferred to the currency of the receiving bank account. 

Example:

To transfer 100,000 Euro bank to Sterling bank (i.e. 88975.89 received into Sterling): 

From Account *: Euro 
To Account *: Sterling 
Payment Type *: Transfer 
Currency *: EUR 
Net Value *: 100,000.00 
Conversion Rate *: 0.8897589 

Users sometimes find this confusing, assuming that they need to select GBP and change the conversion rate. @mshiner has suggested that we show the result of the selections so that the user understands what amounts the system will transfer before committing the transfer.

**Comment by mshiner** [comment]
As well as being a real annoyance it can lead to users making stupid, unforced, errors which are then difficult to resolve without support intervention - we should try to improve the UI to resolve this issue as soon as possible.
