### ISSUE TITLE
Posting accrual GL journal does not update GL balances

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#166]
When an accrual General Ledger journal is posted, the balances for the corresponding accounts are not updated

**Comment by mshiner** [comment]
Steve

I just tried this in the SDL test system and the transactions post but the balances are not updated. I have a hunch that it could be to do with the date of the transaction.

Martyn

**Comment by steveblamey** [comment]
Closed by cf1be1f180cbdebf150b2039e74140624b976799
