### ISSUE TITLE
Various actions should be prevented for leavers in HR

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#170]
It should not be possible to add expenses for employees that have left the company.

The employee drop-down list on the new expense form must be filtered to exclude employees that have left.

**Comment by mshiner** [comment]
This also applied to holiday bookings I have discovered

**Comment by mshiner** [comment]
In addition sidebar actions are still 'open' for expenses, holidays and training plans even if the employee has left.

**Comment by steveblamey** [comment]
CB transactions can also be made to leavers, they continue to appear in the person drop-down when selecting the system company.

**Comment by mshiner** [comment]
I'll pick this one up as part of the HR upgrade I'm still working on currently in the branch 'feature/hr-improvements' branch

**Comment by steveblamey** [comment]
@mshiner I've already got a fix ready so I'll push it into master. A fix has been requested via the helpdesk.

**Comment by mshiner** [comment]
@steveblamey there's a function in the person model to get people with no end_date (or greater than today).... function getCurrent via the getByCompany function

 - is that what you are using?
