### ISSUE TITLE
Australian GST - VAT upgrade

### ISSUE THREAD

**Issue by mshiner** [uzerpllp/uzerp#176]
Added to allow specs etc to be uploaded

Business Activity Statement examples
[OZ BAS.pdf](https://github.com/uzerpllp/uzerp/files/2083506/OZ.BAS.pdf)

**Comment by mshiner** [comment]
A summary of the Australian VAT system and how we might implement in uzERP. 
[Oz GST.pdf](https://github.com/uzerpllp/uzerp/files/2083607/Oz.GST.pdf)

**Comment by mshiner** [comment]
The key changes are going to be to reporting plus one key function which is the ability to do a journal from VAT 'somewhere else' to VAT control to combine payments with PAYG.

The spin off is that in future VAT 'adjustments' are allowed.

**Comment by steveblamey** [comment]
The original requirement for this feature has gone away. It may be raised again in the future.
