### ISSUE TITLE
Add commodity code field to Sales and Purchased Products

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#177]
Add commodity codes (https://www.gov.uk/guidance/classification-of-goods) to sales and purchased products.

- A field to be added to the sales and purchase product
- Add to XML output for sales and purchase invoice (any others?)
- Add to Intrastat reports

**Comment by mshiner** [comment]
Perhaps also add to the so/po order line tables/xml AND the received and despatched lines tables so its easier to report on.

**Comment by steveblamey** [comment]
Commodity codes have been added in release 1.12.

The remaining action is to add them to the VAT reporting

**Comment by steveblamey** [comment]
Moved to #183
