### ISSUE TITLE
Bulk statements doesn't use statement return address and doesn't set email subject

### ISSUE THREAD

**Issue by mshiner** [uzerpllp/uzerp#178]
In the docs here 
https://doc.uzerp.com/Setup/Initial-Setup#system-company_phone-numbers-addresses-and-email-contacts 
it quite clearly states that an entry in the system company emails causes the return address for the emailing of statements to be set rather than using the user's email address.

In addition the email 'subject' is not being set, although if statements are sent from the customer sidebar the subject is set (not sure if the same routine is being used).

Have tested against live systems and this is not happening - not sure if its a regression or not.

**Comment by mshiner** [comment]
Looking at the code in SLCustomersController I can't see any reference to the system company reply-to email address in the printStatement() function

**Comment by steveblamey** [comment]
Looking at the code, the return address was implemented for remittances but not statements.

**Comment by mshiner** [comment]
@steveblamey this is still a live issue and probably needs to be sorted.

**Comment by steveblamey** [comment]
As well as pulling in the email address named 'STATEMENT' from the system company (fallback is the user's email address), the subject needs to be set in printController::process_output().

The output batches are saved in the output_header and output_details tables in the DB. The header _type_ will be 'statement' and the detail line will have _printaction_ 'email'. The process_output() function should add an appropriate subject line to the output parameters.
