### ISSUE TITLE
Incorporate commodity codes in VAT reporting

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#183]
This needs a specification, preferably based on HMRC requirements.

**Comment by mshiner** [comment]
@steveblamey 

HMRC require the weight/value totalled by commodity code, terms and country - I have extended the views in SDLs report db to give the detail required - I canl update the public schema view accordingly.

**Comment by mshiner** [comment]
@steveblamey 

Its then just a question of updating the two functions in VATCollection.php with the additional columns and the view functions in VATController.php with the measure and aggregate fields.

I'll pick this up in the next few weeks.

**Comment by mshiner** [comment]
@steveblamey 

I've sorted this as it was easy to knock off - should I commit the changes to a new branch?

**Comment by mshiner** [comment]
The changes will make the arrivals and despatches screens line up with the HMRC online forms. 

Documentation on how to fill out the online forms and the information required can be downloaded here.....
https://www.uktradeinfo.com/Intrastat/ElectronicSubmission/Internet/Documents/SubmitViaForm.pdf

Full details on Intrastat is here under HMRC Notice 60: Intrastat general guide....
https://www.gov.uk/government/publications/notice-60-intrastat-general-guide/notice-60-intrastat-general-guide
