### ISSUE TITLE
How to installation 1.6

### ISSUE THREAD

**Issue by thislibo** [uzerpllp/uzerp#184]
After downloading the 1.6 installation package, the installation process cannot be started, there is no explanation in the installation documentation, how to perform a local installation

**Comment by thislibo** [comment]
Can uzERP use MySQL database? If so, what should I do?

**Comment by steveblamey** [comment]
@thislibo 1.13 is the latest release, targeting PHP 7. uzERP uses postgresql for its database.

Are you looking to deploy uzERP on a Linux server?

**Comment by thislibo** [comment]
yes i want deploy uzERP on a Linux server , But I didn't find the installation document.

**Comment by steveblamey** [comment]
I hope the following will get you started:

# uzERP Installation

## Install pre-requisites on a fresh install of Ubuntu 18.04

```
$ sudo apt-get install postgresql
$ sudo apt-get install apache2
$ sudo apt-get install fop qpdf ghostscript memcached php-pgsql php-memcached php-curl php-bcmath php-mbstring php-xml
$ sudo apt-get install libapache2-mod-php7.0
```

## Prepare postgresql

Create the database and users

```
$ sudo -u postgres createuser -s www-data
$ sudo -u postgres createuser ooo-data
$ sudo -u postgres createuser readonly
$ sudo -u postgres createuser -s sysadmin
$ sudo -u postgres createdb -O www-data --locale=en_GB.UTF-8 uzerp
```

## Install uzERP

Create release directory

`$ mkdir /var/www/uzerp/1.13`

Get uzERP release package from github

`$ wget -O /tmp/release-uzerp-1.13.tar.gz https://github.com/uzerpllp/uzerp/releases/download/1.13/release-uzerp-1.13.tar.gz`

Expand uzERP release archive to release directory

`$ tar -xf /tmp/release-uzerp-1.13.tar.gz -C /var/www/uzerp/1.13`

Enable write access for Apache on certain directories

```
$ chgrp www-data /var/www/uzerp/1.13/data/cache
$ chgrp www-data /var/www/uzerp/1.13/data/tmp
$ chgrp www-data /var/www/uzerp/1.13/data/users
$ chgrp www-data /var/www/uzerp/1.13/data/templates_c
$ chmod 0770 /var/www/uzerp/1.13/data/cache
$ chmod 0770 /var/www/uzerp/1.13/data/tmp
$ chmod 0770 /var/www/uzerp/1.13/data/users
$ chmod 0770 /var/www/uzerp/1.13/data/templates_c
```

Create the config file

`$ cp /var/www/uzerp/1.13/conf/config-example.php cp /var/www/uzerp/1.13/conf/config.php`

In config.php change `$conf['DB_NAME'] = 'uzerp-base';` to `$conf['DB_NAME'] = 'uzerp';`

## Load a database

```
$ sudo -u postgres pg_restore --dbname=uzerp /var/www/uzerp/1.13/schema/database/postgresql/uzerp-demo-dist.sql`
```

## Configure Apache web server

Add an Apache virtual host, minimal example:

```
<VirtualHost *:80>

  ServerName YOUR_SERVER_NAME

  DocumentRoot "/var/www/uzerp/1.13"

  <Directory "/var/www/uzerp/1.13">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
  </Directory>

  ErrorLog "/var/log/apache2/uzerp_error.log"
  CustomLog "/var/log/apache2/uzerp_access.log" combined 
</VirtualHost>
```

On Ubuntu, create the file `/etc/apache2/sites-available/uzerp.conf` containing the above contents, remebering to change `YOUR_SERVER_NAME` to the DNS name for the site. Then:

```
$ sudo a2ensite uzerp.conf
$ sudo systemctl reload apache2
```
