### ISSUE TITLE
VAT Reverse Charge

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#194]

**Comment by mshiner** [comment]
Steve

Some info here https://www.taxadvisermagazine.com/article/avoiding-trip

I think we should implement in the same way as VAT acquisitions - i.e. have a separate status on the supplier and a new VAT control for items subject to reverse charge

**Comment by mshiner** [comment]
We need to be careful though that we don't double count in Box 7 as the invoice will have already been included.

I think we also need a new list so we can see what the transactions are.

**Comment by mshiner** [comment]
We also need to look at EU distance selling regs - 

https://www.gov.uk/guidance/vat-and-the-single-market-notice-725#section6

**Comment by mshiner** [comment]
Final point - EU distance selling regs are now irrelevant as we are out of the EU and at the end of the TP they will fall away.

**Comment by steveblamey** [comment]
See: https://github.com/uzerpllp/uzerp/commit/d6f88436832b4e8b5af72fe35be75c2bb07985d9
