### ISSUE TITLE
Marking a stock item as obsolete does not update structures (1-369)

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#21]
When marking a stock item as obsolete only the obsolete_date field in st_items is updated when it should also update the end_date field in mf_structures for all structures that use the stock item - otherwise costing will not exclude obsolete stock.

Thus, when an item is marked obsolete any empty end date fields in the structures table should be updated with the same date (obviously if the item has already been changed in the structures table then no need to update the end date field). Perhaps also change remarks field in the structure to note that this was by way of obsolescence.

Note - There's a potential problem with marking items as obsolete in that the end date for the item and structure is set to today, which is fine - except that when re-calculating the latest costs the item is still seen as being active (until midnight). This means that when the item becomes obsolete on the following day, the latest costs will be incorrect.

Currently the only way to correct this would be by re-calculating the latest costs manually via the 'Re-calculate Latest Costs' link on the manufacturing index screen. The only way I can see around this is by setting the end date to yesterday rather than today.

Also, when obsoleting an item the system would need to set end date on linked product line headers/product lines.

**Comment by mshiner** [comment]
Manual procedures (Engineering change control) should deal with these issues.
