### ISSUE TITLE
Verify the validation when substituting/ending a structure item (8-1365)

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#28]
Need to verify the validation when substituting/ending a structure item.

1) A structure item cannot be physically deleted from the system other than by a back end database delete. An end date can be specified after which time it is no longer used, or another item can be substituted (which ends the existing item and inserts a new item from the specified date).

2) A structure item can be edited to specify an end date which is a logical deletion. This can be any date including an end date before the start date. However, there seems to be no validation as to whether the item structure has been used after the entered end date.

3) A structure item cannot be substituted to start on the same day as the existing item but it can start on any other date, before or after the current item.

4) When adding an item to a structure, the costing roll-up will get all the parents of the added structure item and do the cost roll-up; it only needs to do a cost roll-up using the parent that the structure item is added to.

**Comment by mshiner** [comment]
If this rears its head in te future we may have to think on what is happening.
