### ISSUE TITLE
Cannot change postcode on main address

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#53]
Customer trying to change the post code of the main address for an accounts contact (company) receives the following error:

```
ERROR: update or delete on table "address" violates foreign key constraint  "sl_master_billing_address_id_fkey" on table "slmaster" DETAIL: Key (id)=(10115) is still referenced from table "slmaster"
```

**Comment by steveblamey** [comment]
Spoke to @mshiner about this. We'll need to look at the database structure and debug validation done in the PHP code.

In the meantime, the work-around is to add a new party address to the contact, with the correct postcode, and designate that as the new 'main' address

**Comment by mshiner** [comment]
The reason for the error is that the address that is to be modified is already referenced elsewhere in the system (in this case a Sales Invoice). As such the postcode cannot be changed.

If this is a main address then the user can add a new main address and tag the 'incorrect' address as something other than main. Or if not a main address just leave this address as is and add a new (say delivery) address.
