### ISSUE TITLE
Calendar fails to display when using external calendar feeds

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#81]
The calendar will not display properly when an external feed is added, such as google uk holidays, because the request from Javascript is blocked by same-origin policy in some browsers.

**Comment by steveblamey** [comment]
Functionality for adding and managing external calendars in uzERP will be removed.

**Comment by mshiner** [comment]
@steveblamey 

Agreed, but while we're doing this can we the calendar view optional (by select), parameter or user pref driven.

Ideally it'd be great to have an iCal feed published 'somewhere' for consumption by other systems

**Comment by mshiner** [comment]
@steveblamey 

There's a composer fork of this https://icalendar.org/php-library.html

**Comment by steveblamey** [comment]
Moved to #199
