### ISSUE TITLE
GL allows posting to closed periods if front end period validation fails

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#93]
The GL relies on the front end to validate periods allowed and specifically excludes posting to a closed period in period selection drop downs.

However where this breaks down (for instance in the GL Header routine where a template is being used) then the backend does not check if a period is closed BEFORE making the posting.

Two fixes requied
1. Fix the GL Header routine where a header is created from a template AND is an accrual make sure that the accrual period is one month in advance of the posting period.
2. Add a validation check in the backend code that updates the database such that a posting CANNOT be made to a close period under any circumstances.

**Comment by mshiner** [comment]
Do this work in combination with #92
